version: "3.9"
services:
    postgres:
        container_name: dyppis_postgres
        image: postgres:latest
        environment:
            POSTGRES_DB: "dyppis"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "postgres"
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - "2727:5432"
    redis:
        container_name: "dyppis_redis"
        image: redis
        ports:
            - "6379:6379"
    typesense:
        image: typesense/typesense:latest
        environment:
            - TYPESENSE_API_KEY=test
        ports:
            - "8108:8108"
        volumes:
            - ./typesense-data:/data
        command: '--data-dir /data --api-key=xyz --enable-cors'

volumes:
    postgres-data:
    redis-data:
    cache:
        driver: local
