version: "3.9"
services:
    postgres:
        container_name: dyppis_postgres
        image: postgres:latest
        environment:
            POSTGRES_DB: "dyppis"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "postgres"
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - "2727:5432"

    redis:
        container_name: dyppis_redis
        image: redis:latest
        restart: always
        ports:
            - "6379:6379"
        volumes:
            - 'redis_data:/bitnami/redis/data'
        environment:
            - REDIS_PASSWORD=
            - REDIS_PORT=6379
            - REDIS_DATABASES=dyppis

volumes:
    postgres-data:
